apiVersion: v1
kind: Service
metadata:
  name: opensource-intelligence-service
  labels:
    app: opensource-intelligence-service
    tier: backend
spec:
  type: NodePort
  ports:
    - port: -1
  selector:
    app: opensource-intelligence-service
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: opensource-intelligence-service
spec:
  selector:
    matchLabels:
      app: opensource-intelligence-service
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: opensource-intelligence-service
        tier: backend
        deployment: v1
    spec:
      #      serviceAccountName: seclarityservice
      containers:
        - name: opensource-intelligence-service
          image: something/something
          resources:
            requests:
              cpu: 1024m
              memory: 1024Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
              # If your cluster config does not include a dns service, then to
              # instead access environment variables to find service host
              # info, comment out the 'value: dns' line above, and uncomment the
              # line below:
              # value: env
          ports:
            - containerPort: -1
          imagePullPolicy: "Always"
